### ISSUE TITLE
Questions Tâche 2

### ISSUE THREAD

**Issue by NathanRazaf** [umontreal-diro/IFT3913#123]
Ouais j'ai pas trouvé d'autre idée pour poser des questions lol

**Comment by NathanRazaf** [comment]
Et en passant, ça devrait être une page Web ou ça peut juste être un autre fichier .md dont on vous donne le lien dans le README de la tâche 2?

**Comment by bbaudry** [comment]
Bonjour @NathanRazaf 

- pour la documentation: c'est bien d'inclure un lien vers les tests, et le plus important c'est d'expliquer la motivation pour chacun de ces tests
- md et html sont tous les 2 valables

**Comment by NathanRazaf** [comment]
> Bonjour @NathanRazaf
> 
> * pour la documentation: c'est bien d'inclure un lien vers les tests, et le plus important c'est d'expliquer la motivation pour chacun de ces tests
> * md et html sont tous les 2 valables

Donc c'est un lien vers les tests eux-mêmes qu'on demande ou vers les *méthodes* du code qui ont été testées?

**Comment by NathanRazaf** [comment]
Super, merci beaucoup pour la clarification!
Bonne journée
